/*
 * File:        pa4Globals.c
 * Description: Define global variables to calculate the offsets of members
 *              within structs.
 *
 * XXX DO NOT EDIT THIS FILE
 *
 */

#include <stddef.h> /* for offsetof() MACRO */

#include "pa4.h"

size_t statOffset = offsetof( struct fileInfo, statInformation );
size_t mtimeOffset = offsetof( struct stat, st_mtime );
size_t filenameOffset = offsetof( struct fileInfo, filename );
