/*
 * File:        pa4Strings.h
 * Description: Header file containing strings that are displayed to the user.
 *
 * XXX DO NOT EDIT THIS FILE
 *
 */

#ifndef PA4_STRINGS_H /* Header guard */
#define PA4_STRINGS_H


/* Usage strings */
#define STR_USAGE_LONG "\n"\
  "Usage: %s [-d|-u] [-cirst] [inputfiles]\n"\
  "Discard all but one of successive identical lines from the merged\n"\
  "inputfiles writing to stdout.\n"\
  "\n"\
  "Mutually exclusive options (only one of):\n"\
  " -d, --duplicate   only print duplicate lines\n"\
  " -u, --unique      only print unique lines\n"\
  "\n"\
  "Non-mutually exclusive options (any combination of):\n"\
  " -c, --displayCount  prefix lines by the number of occurrences\n"\
  " -i, --ignoreCase    ignore case when comparing adjacent lines\n"\
  " -r, --reverse       perform the file sorting in reverse order\n"\
  " -s, --sort          sort the merged output\n"\
  "                     if -i option specified, ignoring case when sorting\n"\
  " -t, --timeCompare   perform the file sorting based on the modification\n"\
  "                     time instead of the filename\n"\
  "\n"\
  " -h, --help          display this help and exit\n" 

#define STR_USAGE_SHORT "\n"\
  "Usage: %s [-d|-u] [-cirst] [inputfiles] \n"\
  "       %s -h for long help\n"


/* Format string for printing count in displayOutput() */
#define STR_COUNT_PREFIX "%4d "


/* Error strings */
#define STR_ERR_MEM_EXCEEDED "\n\tMemory limit exceeded.\n"
#define STR_ERR_MUTUAL_EX    "\n\tMutually exclusive options were given.\n"


#endif /* PA4_STRINGS_H */
